//! This file is auto-generated by `xtask`. Do not edit manually.
use crate::{types, Server};
use tokio::sync::mpsc;
impl Server {
    ///Sends a `SendChat` action to the server.
    pub async fn send_chat(
        &self,
        target_uuid: String,
        message: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SendChat(types::SendChatAction {
            target_uuid,
            message,
        }))
        .await
    }
    ///Sends a `Teleport` action to the server.
    pub async fn teleport(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::Vec3>>,
        rotation: impl Into<Option<types::Vec3>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::Teleport(types::TeleportAction {
            player_uuid,
            position: position.into(),
            rotation: rotation.into(),
        }))
        .await
    }
    ///Sends a `Kick` action to the server.
    pub async fn kick(
        &self,
        player_uuid: String,
        reason: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::Kick(types::KickAction {
            player_uuid,
            reason,
        }))
        .await
    }
    ///Sends a `SetGameMode` action to the server.
    pub async fn set_game_mode(
        &self,
        player_uuid: String,
        game_mode: types::GameMode,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetGameMode(types::SetGameModeAction {
            player_uuid,
            game_mode: game_mode.into(),
        }))
        .await
    }
    ///Sends a `GiveItem` action to the server.
    pub async fn give_item(
        &self,
        player_uuid: String,
        item: impl Into<Option<types::ItemStack>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::GiveItem(types::GiveItemAction {
            player_uuid,
            item: item.into(),
        }))
        .await
    }
    ///Sends a `ClearInventory` action to the server.
    pub async fn clear_inventory(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::ClearInventory(
            types::ClearInventoryAction { player_uuid },
        ))
        .await
    }
    ///Sends a `SetHeldItem` action to the server.
    pub async fn set_held_item(
        &self,
        player_uuid: String,
        main: impl Into<Option<types::ItemStack>>,
        offhand: impl Into<Option<types::ItemStack>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetHeldItem(types::SetHeldItemAction {
            player_uuid,
            main: main.into(),
            offhand: offhand.into(),
        }))
        .await
    }
    ///Sends a `PlayerSetArmour` action to the server.
    pub async fn player_set_armour(
        &self,
        player_uuid: String,
        helmet: impl Into<Option<types::ItemStack>>,
        chestplate: impl Into<Option<types::ItemStack>>,
        leggings: impl Into<Option<types::ItemStack>>,
        boots: impl Into<Option<types::ItemStack>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetArmour(
            types::PlayerSetArmourAction {
                player_uuid,
                helmet: helmet.into(),
                chestplate: chestplate.into(),
                leggings: leggings.into(),
                boots: boots.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerOpenBlockContainer` action to the server.
    pub async fn player_open_block_container(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerOpenBlockContainer(
            types::PlayerOpenBlockContainerAction {
                player_uuid,
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerDropItem` action to the server.
    pub async fn player_drop_item(
        &self,
        player_uuid: String,
        item: impl Into<Option<types::ItemStack>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerDropItem(
            types::PlayerDropItemAction {
                player_uuid,
                item: item.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerSetItemCooldown` action to the server.
    pub async fn player_set_item_cooldown(
        &self,
        player_uuid: String,
        item: impl Into<Option<types::ItemStack>>,
        duration_ms: i64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetItemCooldown(
            types::PlayerSetItemCooldownAction {
                player_uuid,
                item: item.into(),
                duration_ms,
            },
        ))
        .await
    }
    ///Sends a `SetHealth` action to the server.
    pub async fn set_health(
        &self,
        player_uuid: String,
        health: f64,
        max_health: impl Into<Option<f64>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetHealth(types::SetHealthAction {
            player_uuid,
            health,
            max_health: max_health.into(),
        }))
        .await
    }
    ///Sends a `SetFood` action to the server.
    pub async fn set_food(
        &self,
        player_uuid: String,
        food: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetFood(types::SetFoodAction {
            player_uuid,
            food,
        }))
        .await
    }
    ///Sends a `SetExperience` action to the server.
    pub async fn set_experience(
        &self,
        player_uuid: String,
        level: impl Into<Option<i32>>,
        progress: impl Into<Option<f32>>,
        amount: impl Into<Option<i32>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetExperience(
            types::SetExperienceAction {
                player_uuid,
                level: level.into(),
                progress: progress.into(),
                amount: amount.into(),
            },
        ))
        .await
    }
    ///Sends a `SetVelocity` action to the server.
    pub async fn set_velocity(
        &self,
        player_uuid: String,
        velocity: impl Into<Option<types::Vec3>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SetVelocity(types::SetVelocityAction {
            player_uuid,
            velocity: velocity.into(),
        }))
        .await
    }
    ///Sends a `AddEffect` action to the server.
    pub async fn add_effect(
        &self,
        player_uuid: String,
        effect_type: types::EffectType,
        level: i32,
        duration_ms: i64,
        show_particles: bool,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::AddEffect(types::AddEffectAction {
            player_uuid,
            effect_type: effect_type.into(),
            level,
            duration_ms,
            show_particles,
        }))
        .await
    }
    ///Sends a `RemoveEffect` action to the server.
    pub async fn remove_effect(
        &self,
        player_uuid: String,
        effect_type: types::EffectType,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::RemoveEffect(
            types::RemoveEffectAction {
                player_uuid,
                effect_type: effect_type.into(),
            },
        ))
        .await
    }
    ///Sends a `SendTitle` action to the server.
    pub async fn send_title(
        &self,
        player_uuid: String,
        title: String,
        subtitle: impl Into<Option<String>>,
        fade_in_ms: impl Into<Option<i64>>,
        duration_ms: impl Into<Option<i64>>,
        fade_out_ms: impl Into<Option<i64>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SendTitle(types::SendTitleAction {
            player_uuid,
            title,
            subtitle: subtitle.into(),
            fade_in_ms: fade_in_ms.into(),
            duration_ms: duration_ms.into(),
            fade_out_ms: fade_out_ms.into(),
        }))
        .await
    }
    ///Sends a `SendPopup` action to the server.
    pub async fn send_popup(
        &self,
        player_uuid: String,
        message: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SendPopup(types::SendPopupAction {
            player_uuid,
            message,
        }))
        .await
    }
    ///Sends a `SendTip` action to the server.
    pub async fn send_tip(
        &self,
        player_uuid: String,
        message: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::SendTip(types::SendTipAction {
            player_uuid,
            message,
        }))
        .await
    }
    ///Sends a `PlayerSendToast` action to the server.
    pub async fn player_send_toast(
        &self,
        player_uuid: String,
        title: String,
        message: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendToast(
            types::PlayerSendToastAction {
                player_uuid,
                title,
                message,
            },
        ))
        .await
    }
    ///Sends a `PlayerSendJukeboxPopup` action to the server.
    pub async fn player_send_jukebox_popup(
        &self,
        player_uuid: String,
        message: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendJukeboxPopup(
            types::PlayerSendJukeboxPopupAction {
                player_uuid,
                message,
            },
        ))
        .await
    }
    ///Sends a `PlayerShowCoordinates` action to the server.
    pub async fn player_show_coordinates(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerShowCoordinates(
            types::PlayerShowCoordinatesAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerHideCoordinates` action to the server.
    pub async fn player_hide_coordinates(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerHideCoordinates(
            types::PlayerHideCoordinatesAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerEnableInstantRespawn` action to the server.
    pub async fn player_enable_instant_respawn(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerEnableInstantRespawn(
            types::PlayerEnableInstantRespawnAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerDisableInstantRespawn` action to the server.
    pub async fn player_disable_instant_respawn(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerDisableInstantRespawn(
            types::PlayerDisableInstantRespawnAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetNameTag` action to the server.
    pub async fn player_set_name_tag(
        &self,
        player_uuid: String,
        name_tag: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetNameTag(
            types::PlayerSetNameTagAction {
                player_uuid,
                name_tag,
            },
        ))
        .await
    }
    ///Sends a `PlayerSetScoreTag` action to the server.
    pub async fn player_set_score_tag(
        &self,
        player_uuid: String,
        score_tag: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetScoreTag(
            types::PlayerSetScoreTagAction {
                player_uuid,
                score_tag,
            },
        ))
        .await
    }
    ///Sends a `PlaySound` action to the server.
    pub async fn play_sound(
        &self,
        player_uuid: String,
        sound: types::Sound,
        position: impl Into<Option<types::Vec3>>,
        volume: impl Into<Option<f32>>,
        pitch: impl Into<Option<f32>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlaySound(types::PlaySoundAction {
            player_uuid,
            sound: sound.into(),
            position: position.into(),
            volume: volume.into(),
            pitch: pitch.into(),
        }))
        .await
    }
    ///Sends a `PlayerShowParticle` action to the server.
    pub async fn player_show_particle(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::Vec3>>,
        particle: types::ParticleType,
        block: impl Into<Option<types::BlockState>>,
        face: impl Into<Option<i32>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerShowParticle(
            types::PlayerShowParticleAction {
                player_uuid,
                position: position.into(),
                particle: particle.into(),
                block: block.into(),
                face: face.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerSendScoreboard` action to the server.
    pub async fn player_send_scoreboard(
        &self,
        player_uuid: String,
        title: String,
        lines: Vec<String>,
        padding: impl Into<Option<bool>>,
        descending: impl Into<Option<bool>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendScoreboard(
            types::PlayerSendScoreboardAction {
                player_uuid,
                title,
                lines,
                padding: padding.into(),
                descending: descending.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerRemoveScoreboard` action to the server.
    pub async fn player_remove_scoreboard(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerRemoveScoreboard(
            types::PlayerRemoveScoreboardAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSendMenuForm` action to the server.
    pub async fn player_send_menu_form(
        &self,
        player_uuid: String,
        title: String,
        body: impl Into<Option<String>>,
        buttons: Vec<String>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendMenuForm(
            types::PlayerSendMenuFormAction {
                player_uuid,
                title,
                body: body.into(),
                buttons,
            },
        ))
        .await
    }
    ///Sends a `PlayerSendModalForm` action to the server.
    pub async fn player_send_modal_form(
        &self,
        player_uuid: String,
        title: String,
        body: String,
        yes_text: String,
        no_text: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendModalForm(
            types::PlayerSendModalFormAction {
                player_uuid,
                title,
                body,
                yes_text,
                no_text,
            },
        ))
        .await
    }
    ///Sends a `PlayerSendDialogue` action to the server.
    pub async fn player_send_dialogue(
        &self,
        player_uuid: String,
        title: String,
        body: impl Into<Option<String>>,
        buttons: Vec<String>,
        entity: impl Into<Option<types::EntityRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendDialogue(
            types::PlayerSendDialogueAction {
                player_uuid,
                title,
                body: body.into(),
                buttons,
                entity: entity.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerCloseDialogue` action to the server.
    pub async fn player_close_dialogue(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerCloseDialogue(
            types::PlayerCloseDialogueAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerCloseForm` action to the server.
    pub async fn player_close_form(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerCloseForm(
            types::PlayerCloseFormAction { player_uuid },
        ))
        .await
    }
    ///Sends a `ExecuteCommand` action to the server.
    pub async fn execute_command(
        &self,
        player_uuid: String,
        command: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::ExecuteCommand(
            types::ExecuteCommandAction {
                player_uuid,
                command,
            },
        ))
        .await
    }
    ///Sends a `PlayerStartSprinting` action to the server.
    pub async fn player_start_sprinting(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartSprinting(
            types::PlayerStartSprintingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopSprinting` action to the server.
    pub async fn player_stop_sprinting(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopSprinting(
            types::PlayerStopSprintingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStartSneaking` action to the server.
    pub async fn player_start_sneaking(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartSneaking(
            types::PlayerStartSneakingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopSneaking` action to the server.
    pub async fn player_stop_sneaking(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopSneaking(
            types::PlayerStopSneakingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStartSwimming` action to the server.
    pub async fn player_start_swimming(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartSwimming(
            types::PlayerStartSwimmingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopSwimming` action to the server.
    pub async fn player_stop_swimming(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopSwimming(
            types::PlayerStopSwimmingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStartCrawling` action to the server.
    pub async fn player_start_crawling(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartCrawling(
            types::PlayerStartCrawlingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopCrawling` action to the server.
    pub async fn player_stop_crawling(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopCrawling(
            types::PlayerStopCrawlingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStartGliding` action to the server.
    pub async fn player_start_gliding(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartGliding(
            types::PlayerStartGlidingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopGliding` action to the server.
    pub async fn player_stop_gliding(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopGliding(
            types::PlayerStopGlidingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStartFlying` action to the server.
    pub async fn player_start_flying(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStartFlying(
            types::PlayerStartFlyingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerStopFlying` action to the server.
    pub async fn player_stop_flying(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerStopFlying(
            types::PlayerStopFlyingAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetImmobile` action to the server.
    pub async fn player_set_immobile(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetImmobile(
            types::PlayerSetImmobileAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetMobile` action to the server.
    pub async fn player_set_mobile(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetMobile(
            types::PlayerSetMobileAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetSpeed` action to the server.
    pub async fn player_set_speed(
        &self,
        player_uuid: String,
        speed: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetSpeed(
            types::PlayerSetSpeedAction { player_uuid, speed },
        ))
        .await
    }
    ///Sends a `PlayerSetFlightSpeed` action to the server.
    pub async fn player_set_flight_speed(
        &self,
        player_uuid: String,
        flight_speed: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetFlightSpeed(
            types::PlayerSetFlightSpeedAction {
                player_uuid,
                flight_speed,
            },
        ))
        .await
    }
    ///Sends a `PlayerSetVerticalFlightSpeed` action to the server.
    pub async fn player_set_vertical_flight_speed(
        &self,
        player_uuid: String,
        vertical_flight_speed: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetVerticalFlightSpeed(
            types::PlayerSetVerticalFlightSpeedAction {
                player_uuid,
                vertical_flight_speed,
            },
        ))
        .await
    }
    ///Sends a `PlayerSetAbsorption` action to the server.
    pub async fn player_set_absorption(
        &self,
        player_uuid: String,
        absorption: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetAbsorption(
            types::PlayerSetAbsorptionAction {
                player_uuid,
                absorption,
            },
        ))
        .await
    }
    ///Sends a `PlayerSetOnFire` action to the server.
    pub async fn player_set_on_fire(
        &self,
        player_uuid: String,
        duration_ms: i64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetOnFire(
            types::PlayerSetOnFireAction {
                player_uuid,
                duration_ms,
            },
        ))
        .await
    }
    ///Sends a `PlayerExtinguish` action to the server.
    pub async fn player_extinguish(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerExtinguish(
            types::PlayerExtinguishAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetInvisible` action to the server.
    pub async fn player_set_invisible(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetInvisible(
            types::PlayerSetInvisibleAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetVisible` action to the server.
    pub async fn player_set_visible(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetVisible(
            types::PlayerSetVisibleAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSetScale` action to the server.
    pub async fn player_set_scale(
        &self,
        player_uuid: String,
        scale: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetScale(
            types::PlayerSetScaleAction { player_uuid, scale },
        ))
        .await
    }
    ///Sends a `PlayerSetHeldSlot` action to the server.
    pub async fn player_set_held_slot(
        &self,
        player_uuid: String,
        slot: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSetHeldSlot(
            types::PlayerSetHeldSlotAction { player_uuid, slot },
        ))
        .await
    }
    ///Sends a `PlayerRespawn` action to the server.
    pub async fn player_respawn(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerRespawn(
            types::PlayerRespawnAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerTransfer` action to the server.
    pub async fn player_transfer(
        &self,
        player_uuid: String,
        address: impl Into<Option<types::Address>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerTransfer(
            types::PlayerTransferAction {
                player_uuid,
                address: address.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerKnockBack` action to the server.
    pub async fn player_knock_back(
        &self,
        player_uuid: String,
        source: impl Into<Option<types::Vec3>>,
        force: f64,
        height: f64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerKnockBack(
            types::PlayerKnockBackAction {
                player_uuid,
                source: source.into(),
                force,
                height,
            },
        ))
        .await
    }
    ///Sends a `PlayerSwingArm` action to the server.
    pub async fn player_swing_arm(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSwingArm(
            types::PlayerSwingArmAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerPunchAir` action to the server.
    pub async fn player_punch_air(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerPunchAir(
            types::PlayerPunchAirAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerSendBossBar` action to the server.
    pub async fn player_send_boss_bar(
        &self,
        player_uuid: String,
        text: String,
        health_percentage: impl Into<Option<f32>>,
        colour: impl Into<Option<types::BossBarColour>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerSendBossBar(
            types::PlayerSendBossBarAction {
                player_uuid,
                text,
                health_percentage: health_percentage.into(),
                colour: colour.into().map(|x| x.into()),
            },
        ))
        .await
    }
    ///Sends a `PlayerRemoveBossBar` action to the server.
    pub async fn player_remove_boss_bar(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerRemoveBossBar(
            types::PlayerRemoveBossBarAction { player_uuid },
        ))
        .await
    }
    ///Sends a `PlayerShowHudElement` action to the server.
    pub async fn player_show_hud_element(
        &self,
        player_uuid: String,
        element: types::HudElement,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerShowHudElement(
            types::PlayerShowHudElementAction {
                player_uuid,
                element: element.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerHideHudElement` action to the server.
    pub async fn player_hide_hud_element(
        &self,
        player_uuid: String,
        element: types::HudElement,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerHideHudElement(
            types::PlayerHideHudElementAction {
                player_uuid,
                element: element.into(),
            },
        ))
        .await
    }
    ///Sends a `PlayerOpenSign` action to the server.
    pub async fn player_open_sign(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::BlockPos>>,
        front_side: bool,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerOpenSign(
            types::PlayerOpenSignAction {
                player_uuid,
                position: position.into(),
                front_side,
            },
        ))
        .await
    }
    ///Sends a `PlayerEditSign` action to the server.
    pub async fn player_edit_sign(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::BlockPos>>,
        front_text: String,
        back_text: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerEditSign(
            types::PlayerEditSignAction {
                player_uuid,
                position: position.into(),
                front_text,
                back_text,
            },
        ))
        .await
    }
    ///Sends a `PlayerTurnLecternPage` action to the server.
    pub async fn player_turn_lectern_page(
        &self,
        player_uuid: String,
        position: impl Into<Option<types::BlockPos>>,
        page: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerTurnLecternPage(
            types::PlayerTurnLecternPageAction {
                player_uuid,
                position: position.into(),
                page,
            },
        ))
        .await
    }
    ///Sends a `PlayerHidePlayer` action to the server.
    pub async fn player_hide_player(
        &self,
        player_uuid: String,
        target_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerHidePlayer(
            types::PlayerHidePlayerAction {
                player_uuid,
                target_uuid,
            },
        ))
        .await
    }
    ///Sends a `PlayerShowPlayer` action to the server.
    pub async fn player_show_player(
        &self,
        player_uuid: String,
        target_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerShowPlayer(
            types::PlayerShowPlayerAction {
                player_uuid,
                target_uuid,
            },
        ))
        .await
    }
    ///Sends a `PlayerRemoveAllDebugShapes` action to the server.
    pub async fn player_remove_all_debug_shapes(
        &self,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::PlayerRemoveAllDebugShapes(
            types::PlayerRemoveAllDebugShapesAction { player_uuid },
        ))
        .await
    }
    ///Sends a `WorldSetDefaultGameMode` action to the server.
    pub async fn world_set_default_game_mode(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        game_mode: types::GameMode,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetDefaultGameMode(
            types::WorldSetDefaultGameModeAction {
                world: world.into(),
                game_mode: game_mode.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldSetDifficulty` action to the server.
    pub async fn world_set_difficulty(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        difficulty: types::Difficulty,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetDifficulty(
            types::WorldSetDifficultyAction {
                world: world.into(),
                difficulty: difficulty.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldSetTickRange` action to the server.
    pub async fn world_set_tick_range(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        tick_range: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetTickRange(
            types::WorldSetTickRangeAction {
                world: world.into(),
                tick_range,
            },
        ))
        .await
    }
    ///Sends a `WorldSetBlock` action to the server.
    pub async fn world_set_block(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
        block: impl Into<Option<types::BlockState>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetBlock(
            types::WorldSetBlockAction {
                world: world.into(),
                position: position.into(),
                block: block.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldPlaySound` action to the server.
    pub async fn world_play_sound(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        sound: types::Sound,
        position: impl Into<Option<types::Vec3>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldPlaySound(
            types::WorldPlaySoundAction {
                world: world.into(),
                sound: sound.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldAddParticle` action to the server.
    pub async fn world_add_particle(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::Vec3>>,
        particle: types::ParticleType,
        block: impl Into<Option<types::BlockState>>,
        face: impl Into<Option<i32>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldAddParticle(
            types::WorldAddParticleAction {
                world: world.into(),
                position: position.into(),
                particle: particle.into(),
                block: block.into(),
                face: face.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldSetTime` action to the server.
    pub async fn world_set_time(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        time: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetTime(
            types::WorldSetTimeAction {
                world: world.into(),
                time,
            },
        ))
        .await
    }
    ///Sends a `WorldStopTime` action to the server.
    pub async fn world_stop_time(
        &self,
        world: impl Into<Option<types::WorldRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldStopTime(
            types::WorldStopTimeAction {
                world: world.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldStartTime` action to the server.
    pub async fn world_start_time(
        &self,
        world: impl Into<Option<types::WorldRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldStartTime(
            types::WorldStartTimeAction {
                world: world.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldSetSpawn` action to the server.
    pub async fn world_set_spawn(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        spawn: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetSpawn(
            types::WorldSetSpawnAction {
                world: world.into(),
                spawn: spawn.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldSetBiome` action to the server.
    pub async fn world_set_biome(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
        biome_id: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetBiome(
            types::WorldSetBiomeAction {
                world: world.into(),
                position: position.into(),
                biome_id,
            },
        ))
        .await
    }
    ///Sends a `WorldSetLiquid` action to the server.
    pub async fn world_set_liquid(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
        liquid: impl Into<Option<types::LiquidState>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldSetLiquid(
            types::WorldSetLiquidAction {
                world: world.into(),
                position: position.into(),
                liquid: liquid.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldScheduleBlockUpdate` action to the server.
    pub async fn world_schedule_block_update(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
        block: impl Into<Option<types::BlockState>>,
        delay_ms: i64,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldScheduleBlockUpdate(
            types::WorldScheduleBlockUpdateAction {
                world: world.into(),
                position: position.into(),
                block: block.into(),
                delay_ms,
            },
        ))
        .await
    }
    ///Sends a `WorldBuildStructure` action to the server.
    pub async fn world_build_structure(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        origin: impl Into<Option<types::BlockPos>>,
        structure: impl Into<Option<types::StructureDef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldBuildStructure(
            types::WorldBuildStructureAction {
                world: world.into(),
                origin: origin.into(),
                structure: structure.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryEntities` action to the server.
    pub async fn world_query_entities(
        &self,
        world: impl Into<Option<types::WorldRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryEntities(
            types::WorldQueryEntitiesAction {
                world: world.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryPlayers` action to the server.
    pub async fn world_query_players(
        &self,
        world: impl Into<Option<types::WorldRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryPlayers(
            types::WorldQueryPlayersAction {
                world: world.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryEntitiesWithin` action to the server.
    pub async fn world_query_entities_within(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        r#box: impl Into<Option<types::BBox>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryEntitiesWithin(
            types::WorldQueryEntitiesWithinAction {
                world: world.into(),
                r#box: r#box.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryPlayerSpawn` action to the server.
    pub async fn world_query_player_spawn(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        player_uuid: String,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryPlayerSpawn(
            types::WorldQueryPlayerSpawnAction {
                world: world.into(),
                player_uuid,
            },
        ))
        .await
    }
    ///Sends a `WorldQueryBlock` action to the server.
    pub async fn world_query_block(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryBlock(
            types::WorldQueryBlockAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryBiome` action to the server.
    pub async fn world_query_biome(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryBiome(
            types::WorldQueryBiomeAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryLight` action to the server.
    pub async fn world_query_light(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryLight(
            types::WorldQueryLightAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQuerySkyLight` action to the server.
    pub async fn world_query_sky_light(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQuerySkyLight(
            types::WorldQuerySkyLightAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryTemperature` action to the server.
    pub async fn world_query_temperature(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryTemperature(
            types::WorldQueryTemperatureAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryHighestBlock` action to the server.
    pub async fn world_query_highest_block(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        x: i32,
        z: i32,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryHighestBlock(
            types::WorldQueryHighestBlockAction {
                world: world.into(),
                x,
                z,
            },
        ))
        .await
    }
    ///Sends a `WorldQueryRainingAt` action to the server.
    pub async fn world_query_raining_at(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryRainingAt(
            types::WorldQueryRainingAtAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQuerySnowingAt` action to the server.
    pub async fn world_query_snowing_at(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQuerySnowingAt(
            types::WorldQuerySnowingAtAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryThunderingAt` action to the server.
    pub async fn world_query_thundering_at(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryThunderingAt(
            types::WorldQueryThunderingAtAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryLiquid` action to the server.
    pub async fn world_query_liquid(
        &self,
        world: impl Into<Option<types::WorldRef>>,
        position: impl Into<Option<types::BlockPos>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryLiquid(
            types::WorldQueryLiquidAction {
                world: world.into(),
                position: position.into(),
            },
        ))
        .await
    }
    ///Sends a `WorldQueryDefaultGameMode` action to the server.
    pub async fn world_query_default_game_mode(
        &self,
        world: impl Into<Option<types::WorldRef>>,
    ) -> Result<(), mpsc::error::SendError<types::PluginToHost>> {
        self.send_action(types::action::Kind::WorldQueryDefaultGameMode(
            types::WorldQueryDefaultGameModeAction {
                world: world.into(),
            },
        ))
        .await
    }
}
