use anyhow::Result;
use heck::ToSnakeCase;
use quote::{format_ident, quote};
use std::path::PathBuf;
use syn::File;

use crate::utils::{find_nested_enum, get_variant_type_path, write_formatted_file};

pub fn generate_handler_trait(ast: &File, output_path: &PathBuf) -> Result<()> {
    println!(
        "Generating Event Handler trait in: {}...",
        output_path.to_string_lossy()
    );

    let event_payload_enum = find_nested_enum(ast, "event_envelope", "Payload")?;

    let mut event_handler_fns = Vec::new();
    let mut dispatch_fn_match_arms = Vec::new();

    for variant in &event_payload_enum.variants {
        let ident = &variant.ident;
        let ty_path = get_variant_type_path(variant)?.segments.last();
        let ident_formatted = ident.to_string().to_snake_case();
        let handler_fn_name = format_ident!("on_{}", ident_formatted);
        let doc_string = format!("Handler for the `{}` event.", ident);

        event_handler_fns.push(quote! {
            #[doc = #doc_string]
            async fn #handler_fn_name(
                &self,
                _server: &Server,
                _event: &mut EventContext<types::#ty_path>,
            ) {}
        });

        dispatch_fn_match_arms.push(quote! {
            types::event_envelope::Payload::#ident(e) => {
                let mut context = EventContext::new(&envelope.event_id, e);
                handler.#handler_fn_name(server, &mut context).await;
                server.send_event_result(context).await.ok();
            },
        })
    }

    let file = quote! {
        // This file is auto-generated by `xtask`. Do not edit manually.
        #![allow(unused_variables)]
        use crate::{event::EventContext, types, Server, PluginSubscriptions};
        use async_trait::async_trait;

        #[async_trait]
        pub trait PluginEventHandler: PluginSubscriptions + Send + Sync {
            #(#event_handler_fns)*
        }

        #[doc(hidden)]
        pub async fn dispatch_event(server: &Server, handler: &impl PluginEventHandler, envelope: &types::EventEnvelope) {
            let Some(payload) = &envelope.payload else {
                return;
            };
            match payload {
                #(#dispatch_fn_match_arms)*
            }
        }
    };

    // write our generated code.
    write_formatted_file(output_path, file.to_string())?;
    println!(
        "Successfully generated Event Handler Trait in: {}.",
        output_path.to_string_lossy()
    );
    Ok(())
}
