//! Generate the `EventHandler` trait and `dispatch_event` function.
//!
//! This module walks the prost-generated `event_envelope::Payload` enum and
//! produces:
//! - A trait method per event (e.g. `async fn on_chat(...)`).
//! - A single `dispatch_event` function that decodes envelopes and forwards
//!   them into the correct handler method.
//!
//! The generated code lives in `src/event/handler.rs` and is considered
//! part of the public SDK surface, so changes here must keep the trait
//! shape and dispatch semantics stable.

use anyhow::Result;
use heck::ToSnakeCase;
use quote::{format_ident, quote};
use std::path::PathBuf;
use syn::File;

use crate::utils::{find_nested_enum, get_variant_type_path, prettify_code};

/// Generate the `EventHandler` trait and the central `dispatch_event`
/// function from the prost-generated `EventEnvelope::Payload` enum.
pub fn generate_handler_trait(ast: &File, output_path: &PathBuf) -> Result<()> {
    println!(
        "Generating Event Handler trait in: {}...",
        output_path.to_string_lossy()
    );

    let code = generate_handler_trait_tokens(ast)?;

    // write our generated code.
    let file = prettify_code(code)?;

    std::fs::write(output_path, file)?;

    println!(
        "Successfully generated Event Handler Trait in: {}.",
        output_path.to_string_lossy()
    );
    Ok(())
}

fn generate_handler_trait_tokens(ast: &File) -> Result<String> {
    let event_payload_enum = find_nested_enum(ast, "event_envelope", "Payload")?;

    let mut event_handler_fns = Vec::new();
    let mut dispatch_fn_match_arms = Vec::new();

    for variant in &event_payload_enum.variants {
        let ident = &variant.ident;
        let ty_path = get_variant_type_path(variant)?.segments.last();
        let ident_formatted = ident.to_string().to_snake_case();
        let handler_fn_name = format_ident!("on_{}", ident_formatted);
        let doc_string = format!("Handler for the `{}` event.", ident);

        event_handler_fns.push(quote! {
            #[doc = #doc_string]
            async fn #handler_fn_name(
                &self,
                _server: &Server,
                _event: &mut EventContext<'_, types::#ty_path>,
            ) { }
        });

        let match_arm = if ident == "Command" {
            quote! {
                types::event_envelope::Payload::#ident(e) => {
                    let mut context = EventContext::new(
                        &envelope.event_id,
                        e,
                        server.sender.clone(),
                        server.plugin_id.clone(),
                    );

                    context.send_ack_if_needed().await;

                    // Try registered commands first
                    let handled = handler.dispatch_commands(server, &mut context).await;

                    // Fall back to on_command for unregistered/dynamic commands
                    if !handled {
                        handler.#handler_fn_name(server, &mut context).await;
                    }
                },
            }
        } else {
            quote! {
                types::event_envelope::Payload::#ident(e) => {
                    let mut context = EventContext::new(
                        &envelope.event_id,
                        e,
                        server.sender.clone(),
                        server.plugin_id.clone(),
                    );
                    handler.#handler_fn_name(server, &mut context).await;
                    context.send_ack_if_needed().await;
                },
            }
        };

        dispatch_fn_match_arms.push(match_arm);
    }

    Ok(quote! {
        //! This file is auto-generated by `xtask`. Do not edit manually.
        #![allow(async_fn_in_trait)]
        use crate::{event::EventContext, types, Server, EventSubscriptions, command::CommandRegistry};

        pub trait EventHandler: EventSubscriptions + Send + Sync {
            #(#event_handler_fns)*
        }

        #[doc(hidden)]
        pub async fn dispatch_event(server: &Server, handler: &(impl EventHandler + CommandRegistry), envelope: &types::EventEnvelope) {
            let Some(payload) = &envelope.payload else {
                return;
            };
            match payload {
                #(#dispatch_fn_match_arms)*
            }
        }
    }.to_string())
}

#[cfg(test)]
mod tests {
    use super::*; // Import your generator functions
    use syn::{parse_file, File};

    fn setup_test_ast() -> File {
        let mock_code = include_str!("../assets/mock_prost.rs");

        parse_file(mock_code).expect("Failed to parse mock AST")
    }

    #[test]
    fn snapshot_test_generate_event_handler() {
        let ast = setup_test_ast();

        let generated_code =
            generate_handler_trait_tokens(&ast).expect("Generator function failed");

        let prettified_code = prettify_code(generated_code).expect("Invalid code being produced.");

        insta::assert_snapshot!("event_handler", prettified_code);
    }
}
